# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-17 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_secondpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondpost',
            old_name='email',
            new_name='email_val',
        ),
    ]
